version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "12000:3000"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    command: sh -c "npm run dev"
volumes:
  node_modules:
